---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
      version: blue
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        version: blue
    spec:
      containers:
      - name: nginx
        image: chaudharishubham2911/nginx:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    app: nginx
    version: blue
  type: NodePort
  ports:
  - nodePort: 31113
    port: 80
    targetPort: 80
